---
title: "Tidyverse"
author: "Ramprasath"
---
-----------------------------------------
#Sales Analysis, Tidyverse Challenge
-----------------------------------------

# Libraries

Load the following libraries. 
```{r}
library(tidyverse)
library(readxl)

```

# Import Files
```{r}
bikes_tbl <- read_excel(path = "./../../00_data/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("./../../00_data/01_raw_data/orderlines.xlsx")
bikeshops_tbl  <- read_excel("./../../00_data/01_raw_data/bikeshops.xlsx")
```

#joining data
```{r}
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))
```

#wrangling data
```{r}
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>% 
  separate(col = location, 
           into = c("City","State"),
           sep = ",") %>%
  mutate(total.price = price * quantity) %>%
  select(-...1,-gender) %>%
  select(-ends_with(".id")) %>%
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))
```

# Manipulation of data (sales by state)
```{r}
library(lubridate)

sales_by_state_tbl <- bike_orderlines_wrangled_tbl %>%
  select(State,total_price) %>%
  group_by(State) %>%
  summarize(sales = sum(total_price)) %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))
sales_by_state_tbl
```

# Visualize sales by state data

```{r plot, fig.width=10, fig.height=7}
sales_by_state_tbl %>% ggplot(aes(x = State, y =sales)) +
  geom_col(fill = "#2DC6D6") + 
  geom_label(aes(label = sales_text)) +
  geom_smooth(method = "lm", se = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by State",
    subtitle = "State wise trend of sales",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )
```

#Manipulate sales by state and location data

```{r}
sales_by_year_state_tbl <- bike_orderlines_wrangled_tbl %>%
  select(order_date,total_price,State) %>%
  mutate(year = year(order_date)) %>%
  group_by(year,State) %>%
  summarise(sales = sum(total_price)) %>% 
  ungroup() %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))


sales_by_year_state_tbl
```

# Visualize sales by state data

```{r plot2, fig.width=10, fig.height=7}
sales_by_year_state_tbl %>% ggplot(aes(x = year, y = sales, fill = State)) + 
  geom_col() +
  facet_wrap(~ State) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €"))+
  labs(
    title = "Revenue by year and state",
    subtitle = "Each state different sales trend",
    fill = "State" 
  )
```